### ISSUE TITLE
debug.html is not working

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#12]
`ReferenceError: Can't find variable: WorkerUI:
debug.html:77`

**Comment by marcelhollerbach** [comment]
possible that the worker_ui.js wasnt found and not downloaded?

**Comment by simonkorz** [comment]
this should be resolved, as leander seamingly opened debug.html from the wrong directory.

**Comment by LeanderK** [comment]
my fault, opened debug.html in src and not in build
