### ISSUE TITLE
wrong ws url

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#18]
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dummydummy, line 0)
http://192.168.99.100:3333/http://192.168.99.100:3333/http://192.168.99.100:3333/http://192.168.99.100:3333/http://192.168.99.100:3333/emails/dummydummy`

when trying to submit an email

**Comment by LeanderK** [comment]
happens very often

**Comment by LeanderK** [comment]
maybe it has something to do with clicking loadView

Update: i don't recognise a pattern

**Comment by simonkorz** [comment]
resolved #25
