### ISSUE TITLE
provide skip buttom

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#22]
currently there is no skip-button

**Comment by simonkorz** [comment]
That's strange. I'm pretty sure I had one, but I cant remember when I saw one the last time.

**Comment by LeanderK** [comment]
haha :D

**Comment by LeanderK** [comment]
ok, its only missing in the answer-view

**Comment by simonkorz** [comment]
okay found the problem

**Comment by kelunik** [comment]
It's there, but gets hidden very fast after initial display.
