### ISSUE TITLE
answer view to submit urls

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#30]
when submitting urls it would be nice if the answer-view would reduce the textfield to a one-liner.

**Comment by simonkorz** [comment]
actually this should already be the case.

**Comment by marcelhollerbach** [comment]
***_sniff**_*\* I can smell a buggerino

**Comment by simonkorz** [comment]
The ui checks for `answerType == "images"`.
I have never been sure what values `answer_type` can have.

**Comment by LeanderK** [comment]
the answer type is a mime type, so it can be `images`, `images/*` or `images/jpeg`

**Comment by simonkorz** [comment]
But what does the worker service send, if I choose answer type to be images in control ui?

**Comment by LeanderK** [comment]
this is what the worker-service can send you. You have to understand all. Quoting the documentation of the ws: the answer type, if set this means the worker submits a link pointing to a resource with the mime-type answerType.

**Comment by simonkorz** [comment]
I don't understand why there are multiple possibilities if I can only choose it to be images or answer in the control ui. What decides which answertypes are sent by the ws?

**Comment by LeanderK** [comment]
well, the control-ui is not what defines the database-layout/ws api here. I save the mime-type in the database or null!

**Comment by simonkorz** [comment]
Okay! @phimonk w0rk, w0rk!
But then you should have used mime type text/\* for normal answers instead of null. just to be explicit and consistent.

**Comment by LeanderK** [comment]
no, thats not how it is defined. text/\* would also be valid, but the the answer would a a link pointing to a resource where the mime type is text/*
