### ISSUE TITLE
worker-ui displays Image-view

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/worker-ui#38]
the worker-ui displays image for answer-type null in answer and rating

**Comment by simonkorz** [comment]
I didn't know of the issuer here, but i spotted the error to. Was the same with answer view. fixed by commit 0b0ba21db9ed03cfbd699278671ece1471f55813

**Comment by LeanderK** [comment]
still happens under rating view

**Comment by simonkorz** [comment]
can't reproduce

**Comment by TheRittler** [comment]
is this now still a bug or has this been fixed?
